// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqDumwdw2ZvSZLUu-UXemo_i_kb6yRZv8',
    appId: '1:853381534285:web:afb43e3d0aef323b95c204',
    messagingSenderId: '853381534285',
    projectId: 'ecommerceapp-e8618',
    authDomain: 'ecommerceapp-e8618.firebaseapp.com',
    storageBucket: 'ecommerceapp-e8618.firebasestorage.app',
    measurementId: 'G-DPC66GDR0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0H0Iyar7RXyVfS734qCybmPq_FiPKixo',
    appId: '1:853381534285:android:4785135cd7e6e87895c204',
    messagingSenderId: '853381534285',
    projectId: 'ecommerceapp-e8618',
    storageBucket: 'ecommerceapp-e8618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJ_o22nEv4oLWAKybZbPQ8ovJ6qyXOl4',
    appId: '1:853381534285:ios:001a9c932ff3b3dd95c204',
    messagingSenderId: '853381534285',
    projectId: 'ecommerceapp-e8618',
    storageBucket: 'ecommerceapp-e8618.firebasestorage.app',
    androidClientId: '853381534285-fkm3t4vpekjk7rfhma2gofi6hceb7gg0.apps.googleusercontent.com',
    iosClientId: '853381534285-qt9a05mak5h51rhoc2fbivvoo0d9pu03.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommApp',
  );

}